import type { Restaurant, Review } from '@/types'

export const restaurantStore: Restaurant[] = [
  {
    id: '1',
    name: 'Jay Fai',
    nameTh: 'เจ๊ไฝ',
    address: '327 Maha Chai Rd, Samran Rat, Phra Nakhon',
    addressTh: '327 ถ.มหาไชย แขวงสำราญราษฎร์ เขตพระนคร',
    district: 'Phra Nakhon',
    districtTh: 'พระนคร',
    lat: 13.7530,
    lng: 100.5020,
    krapaoScore: {
      overall: 9.1,
      aromatic: 9.5,
      wok: 9.8,
      heat: 8.5,
      purity: 9.0,
      protein: 9.2,
      egg: 8.5,
    },
    reviewCount: 42,
  },
  {
    id: '2',
    name: 'Thipsamai',
    nameTh: 'ทิพย์สมัย',
    address: '313 Mahachai Rd, Wang Burapha Phirom, Phra Nakhon',
    addressTh: '313 ถ.มหาไชย แขวงวังบูรพาภิรมย์ เขตพระนคร',
    district: 'Phra Nakhon',
    districtTh: 'พระนคร',
    lat: 13.7480,
    lng: 100.5030,
    krapaoScore: {
      overall: 8.2,
      aromatic: 8.5,
      wok: 8.8,
      heat: 7.5,
      purity: 8.0,
      protein: 7.8,
      egg: 8.6,
    },
    reviewCount: 28,
  },
  {
    id: '3',
    name: 'Phed Mark',
    nameTh: 'เผ็ดมาก',
    address: '16 Soi Ari 4, Phahonyothin Rd, Phaya Thai',
    addressTh: '16 ซ.อารีย์ 4 ถ.พหลโยธิน แขวงพญาไท',
    district: 'Phaya Thai',
    districtTh: 'พญาไท',
    lat: 13.7757,
    lng: 100.5474,
    krapaoScore: {
      overall: 8.7,
      aromatic: 9.0,
      wok: 8.5,
      heat: 9.2,
      purity: 8.5,
      protein: 8.0,
      egg: 9.0,
    },
    reviewCount: 19,
  },
  {
    id: '4',
    name: 'Polo Fried Chicken',
    nameTh: 'ไก่ทอดโปโล',
    address: '137/1-3 Witthayu Rd, Lumphini, Pathum Wan',
    addressTh: '137/1-3 ถ.วิทยุ แขวงลุมพินี เขตปทุมวัน',
    district: 'Pathum Wan',
    districtTh: 'ปทุมวัน',
    lat: 13.7410,
    lng: 100.5470,
    krapaoScore: {
      overall: 7.8,
      aromatic: 7.5,
      wok: 8.2,
      heat: 7.0,
      purity: 8.5,
      protein: 8.0,
      egg: 7.6,
    },
    reviewCount: 15,
  },
  {
    id: '5',
    name: 'Soei Restaurant',
    nameTh: 'ร้านเสริม',
    address: '10/1 Soi Ari, Sam Sen Nai, Phaya Thai',
    addressTh: '10/1 ซ.อารีย์ แขวงสามเสนใน เขตพญาไท',
    district: 'Phaya Thai',
    districtTh: 'พญาไท',
    lat: 13.7800,
    lng: 100.5490,
    krapaoScore: {
      overall: 7.5,
      aromatic: 7.0,
      wok: 7.8,
      heat: 7.5,
      purity: 7.5,
      protein: 7.8,
      egg: 7.4,
    },
    reviewCount: 11,
  },
]

export const reviewStore: Review[] = [
  {
    id: 'r1',
    restaurantId: '1',
    authorName: 'Somchai T.',
    comment: 'The holy basil fragrance is incredible — authentic variety, not the Italian impostor.',
    visitedAt: '2026-05-10',
    scores: { aromatic: 9.5, wok: 10, heat: 8, purity: 9, protein: 9.5, egg: 8.5 },
    purityOffenders: [],
    heatRating: { specified: true, match: 3 },
  },
  {
    id: 'r2',
    restaurantId: '1',
    authorName: 'Ploy S.',
    comment: 'Wok hei is real here. You can smell the pan from across the room.',
    visitedAt: '2026-06-02',
    scores: { aromatic: 9, wok: 10, heat: 9, protein: 9, egg: 9 },
    purityOffenders: [],
  },
  {
    id: 'r3',
    restaurantId: '2',
    authorName: 'Nattapong K.',
    comment: 'Good but the egg could use a bit more crispiness on the edges.',
    visitedAt: '2026-05-20',
    scores: { aromatic: 8, wok: 9, heat: 7, purity: 8, protein: 8, egg: 8 },
    purityOffenders: [],
    heatRating: { specified: false },
  },
  {
    id: 'r4',
    restaurantId: '3',
    authorName: 'Wan J.',
    comment: 'True firebrand krapao — the chillies here are not for the faint of heart.',
    visitedAt: '2026-06-15',
    scores: { heat: 9.5, aromatic: 9, wok: 8.5, purity: 8, protein: 7.5 },
    purityOffenders: [],
    heatRating: { specified: true, match: 5 },
  },
]
